# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4aa9acab1582eef4c0db8bd7545eb12569b5b3796953f083de1077dbe7b04b9c1e2a71677641f5f45f36bd4c07cce2c0dff91c17a08f95ac577165f52aa3ca5

test:
  secret_key_base: 047fd4e89e8bc02637fb75c44ff9f6f4be0ffe248b84f640f31dee6f76d18e08442bad7eed95c1ad9a620c38205b8a2f12f5c9edd2090f6de93e477b251a0b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
